projects:
  ampapp:
    schemaPath: src\graphql\schema.json
    includes:
      - ./app/src/main/graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
